### ISSUE TITLE
Errore nell'utilizzo del file

### ISSUE THREAD

**Issue by Giorgio792** [Tecnologica-Mente/PDFGrabber_Launcher#1]
Dopo aver scaricato con il comando "1" i file richiesti, usando il comando "2" mi da il seguente errore:
Traceback (most recent call last):
```
  File "C:\Users\ruber\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\pdfgrabber-master\main.py", line 1, in <module>
    import utils
  File "C:\Users\ruber\Downloads\PDFGrabber_Launcher-main\PDFGrabber_Launcher-main\pdfgrabber-master\utils.py", line 2, in <module>
    import fitz
ModuleNotFoundError: No module named 'fitz'
```
come devo fare?

**Comment by Tecnologica-Mente** [comment]
Ciao. Prova in questo modo.
Apri con il blocco note il file "requirements.txt", aggiungi una nuova riga in fondo, scrivi la parola "fitz" (senza doppi apici) e salvalo. Poi prova nuovamente ad eseguire il programma cliccando il comando "1" e poi il "2". Vedi se risolvi.

**Comment by Giorgio792** [comment]
L'ho appena fatto e sembra che abbia installato fitz, ma quando provo a schiacciare "2" mi da lo stesso errore.

**Comment by Tecnologica-Mente** [comment]
Mi pare strano. Comunque il modulo fitz dovrebbe essere caricato automaticamente con il modulo PyMuPDF. Prova con un altro PC, io ho provato e funziona correttamente
